---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiops
  namespace: sky-firmament
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aiops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: aiops
  namespace: sky-firmament

