apiVersion: v1
kind: ConfigMap
metadata:
  name: aiops-config
  namespace: sky-firmament
  labels:
    app: aiops
    type: api
data:
  config.json: |-
    {
       "global": {
             "mysql_host":"192.168.254.44:31786",
             "mysql_user":"root",
             "mysql_pwd":"password",
             "mysql_db":"skyform_aiops",
             "params": [
             "--es_hosts=10.15.1.30:9200",
             "--timename=createTime"
             ]
        },
		"DB_map": [
         {
           "table_name": "monitor_obj",
           "column_map": [
                {
                    "column": "host",
                    "parameter": "--host",
                },
                {
                    "column": "host",
                    "parameter": "--host",
                },
                {
                    "column": "instance_name",
                    "parameter": "--instance_name",
                },
                {
                    "column": "metric",
                    "parameter": "--kpi",
                },
                {
                    "column": "es_index",
                    "parameter": "--index",
                },
                {
                    "column": "es_type",
                    "parameter": "--doc_type",
                },
                {
                    "column": "sample_rate",
                    "parameter": "--freq",
                }
            ]
          }
       ]
    }
  application.json: |-
    {
        "app": [{
             "application": "capacity_prediction",
             "id": 2,
             "image": "registry.harbor:5000/sky-aiops/capacity:zw180507",
             "cmd": ["python","main.py"],
             "cron": "*/30 * * * *",
             "cpuRequest": "100m",
             "params": []
        },
        {
             "application": "baseline",
             "id": 1,
             "image": "registry.harbor:5000/sky-aiops/baseline:zw180507",
             "cmd": ["python","main.py"],
             "cron": "*/30 * * * *",
             "cpuRequest": "100m",  
             "params":[]
        }]
    }
