apiVersion: v1
kind: ConfigMap
metadata:
  name: aiops-config
  namespace: sky-firmament
  labels:
    app: aiops
    type: api
data:
  config.json: |-
    {
       "global": {
             "namespace":"default",
             "es_hosts":"10.15.1.30:9200",
             "index":"metric",
             "doc_type":"metric",
             "timename":"createTime",
             "mysql_host":"10.15.21.240:32015",
             "mysql_user":"root",
             "mysql_pwd":"password",
             "mysql_db":"skyform_aiops"
        }
    }
  application.json: |-
    {
        "app": [{
             "application": "capacity_prediction",
             "id": 2,
             "image": "registry.harbor:5000/sky-aiops/capacity:zw180507",
             "cmd": ["python","main.py"],
             "cron": "*/30 * * * *",
             "params": [
             "--period=100",
             "--freq=1T",
			 "--timedelta=144000",
             "--confidence_interval=0.9",
             "--threshold=9000"]
        },
        {
             "application": "baseline",
             "id": 1,
             "image": "registry.harbor:5000/sky-aiops/baseline:zw180507",
             "cmd": ["python","main.py"],
             "cron": "*/30 * * * *",
             "params": [
             "--period=100",
             "--freq=1T",
			 "--timedelta=144000",
             "--confidence_interval=0.9",
             "--threshold=9000"]
        }]
    }
